Player class
andresgamo/carWarGame pull request #2
Opened 2023-08-24 02:25 UTC by andresgamo

2023-08-24 15:27 UTC, jujopalacio commented
@andresgamo not sure what is the intention of this PR, it is not easy to understand the title, there is no description and the changes are not different than the other PR except for the commented code.

2023-08-24 18:52 UTC, andresgamo commented
> @andresgamo not sure what is the intention of this PR, it is not easy to understand the title, there is no description and the changes are not different than the other PR except for the commented code.

Updated the title and descriptions. Please consider the last commit. The first three are from shuffleCards branch. I merged shuffleCards brach into playerClass branch.

2023-08-28 14:48 UTC, jujopalacio requested changes
check my comments

2023-08-28 14:48 UTC, jujopalacio commented on carWarGame.py
> +    values = {'2':2,'3':3,'4':4,'5':5,'6':6,'7':7,'8':8,'9':9,'10':10,'J':11,'Q':12,'K':13,'A':14}
@andresgamo please investigate black and reformat your code, please.

https://black.readthedocs.io/en/stable/

2023-08-28 14:48 UTC, jujopalacio commented on carWarGame.py
> +    ranks = ['2','3','4','5','6','7','8','9','10','J','Q','K','A']
use black to reformat your code.

2023-08-28 14:48 UTC, jujopalacio commented on carWarGame.py
>              print(card)
please use logging instead of prints.

```
import logging
logger = logging.getLogger(__file__)
logger.debug("not so important log")
logger.info("interesting log")
logger.warning("important log")
logger.error("must check log")
```

2023-08-28 14:48 UTC, jujopalacio commented on carWarGame.py
> +    # deck = Deck()
@andresgamo avoid including commented code in your repo.

2023-08-28 22:26 UTC, jujopalacio approved these changes
looks good to me.

2023-08-28 23:26 UTC, merged